# RT-Thread building script for bridge

import os
from building import *

Import('rtconfig')

cwd = GetCurrentDir()
list = os.listdir(cwd)

# add common code files
group = SConscript(os.path.join('common', 'SConscript'))
group = SConscript(os.path.join('cortex-m4', 'SConscript'))

Return('group')
